[global]
mon_initial_members=ceph01,ceph02,ceph03
mon_host=10.1.10.100,0.1.10.101,0.1.10.102
public_network=10.1.10.0/24
auth_cluster_required=cephx
auth_service_required=cephx
auth_client_required=cephx
osd_pool_default_size=3
osd_pool_default_min_size=2
osd_pool_default_pg_num=128
osd_pool_default_pgp_num=128
storage_type=bluestore
osd_objectstore=bluestore
osd_mkfs_type=xfs
bluestore_block_size=5628755968
fsid = 58986a6f-4686-4815-9a90-8820536a55f4
