# SPDX-License-Identifier: MIT-0
---
# tasks file for roles/configure_mon
- name: Include leader tasks for leader nodes
  ansible.builtin.import_tasks: leader.yml
  when: inventory_hostname in groups['leader']

- name: Include follower tasks for follower nodes
  ansible.builtin.import_tasks: followers.yml
  when: inventory_hostname in groups['followers']
