download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/ceph-automation-1.1.0.tar.gz
format_version: 1.0.0
name: automation
namespace: ceph
server: https://galaxy.ansible.com/api/
signatures: []
version: 1.1.0
version_url: /api/v3/plugin/ansible/content/published/collections/index/ceph/automation/versions/1.1.0/
