[global]
mon_initial_members=ceph01,ceph02,ceph03
mon_host=10.1.10.100,0.1.10.101,0.1.10.102
public_network=10.1.10.0/24
auth_cluster_required=cephx
auth_service_required=cephx
auth_client_required=cephx
osd_pool_default_size=3
osd_pool_default_min_size=2
osd_pool_default_pg_num=128
osd_pool_default_pgp_num=128
storage_type=bluestore
osd_objectstore=bluestore
osd_mkfs_type=xfs
bluestore_block_size=5628755968
fsid = 3f7ed9bb-baf7-4826-a8e6-057452ee3668
# BEGIN RGW config for ceph01
[client.rgw.ceph01]
host = ceph01
keyring = /etc/ceph/ceph.client.radosgw.keyring
log file = /var/log/radosgw/client.radosgw.gateway.log
rgw frontends = civetweb port=10.1.10.100:8080
# END RGW config for ceph01
# BEGIN RGW config for ceph02
[client.rgw.ceph02]
host = ceph02
keyring = /etc/ceph/ceph.client.radosgw.keyring
log file = /var/log/radosgw/client.radosgw.gateway.log
rgw frontends = civetweb port=10.1.10.101:8080
# END RGW config for ceph02
# BEGIN RGW config for ceph03
[client.rgw.ceph03]
host = ceph03
keyring = /etc/ceph/ceph.client.radosgw.keyring
log file = /var/log/radosgw/client.radosgw.gateway.log
rgw frontends = civetweb port=10.1.10.102:8080
# END RGW config for ceph03
